# Generated by Django 2.2.1 on 2019-05-25 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jedi_department', '0002_padawan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padawan',
            name='candidate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
